name: Deploy to GitHub Pages

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Chọn phiên bản PHP bạn đang sử dụng

    - name: Install Dependencies
      run: composer install

    - name: Copy Environment File
      run: cp .env.example .env  # Nếu không có .env, bạn có thể tạo một bản sao từ .env.example và điều chỉnh cấu hình

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Run Migrations and Seed
      run: php artisan migrate --seed

    - name: Deploy to GitHub
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push
